### PR TITLE
Replace `sklearn` dependency with `scikit-learn`

### PR DESCRIPTION
**Pull request by ivyleavedtoadflax**
Install `sklearn` is now deprecated, this switches to `scikit-learn`.

### CODE REVIEW

**Comment by nsorros** [comment]
Might be good to update the version as well

**Review by nsorros — APPROVED** [review]

**Comment by ivyleavedtoadflax** [comment]
of python?

**Comment by ivyleavedtoadflax** [comment]
or do you mean pin scikit-learn

**Comment by ivyleavedtoadflax** [comment]
ahh yes, good point.

**Pull request merged**
